<?php

if (!defined('CROWD_FUNDRAISER_SLUG'))
    define('CROWD_FUNDRAISER_SLUG', 'crowd-fundraiser');


if (!defined('CROWD_FUNDRAISER_VERSION_KEY'))
    define('CROWD_FUNDRAISER_VERSION_KEY', 'CROWD_FUNDRAISER_VERSION_KEY');

if (!defined('CROWD_FUNDRAISER_VERSION_NUM'))
    define('CROWD_FUNDRAISER_VERSION_NUM', '1.0.0');